Update deploy

diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -4,32 +4,32 @@
 # up again.  This script gets executed directly, so it could be python, php,
 # ruby, etc.
 
-set -e
+#set -e
 
-if [ -z "$OPENSHIFT_POSTGRESQL_DB_HOST" ]
-then
-echo 1>&2
-    echo "Could not find mysql database. Please run:" 1>&2
-    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c postgresql-8.4" 1>&2
-    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
-    echo 1>&2
-fi
+#if [ -z "$OPENSHIFT_POSTGRESQL_DB_HOST" ]
+#then
+#echo 1>&2
+#    echo "Could not find mysql database. Please run:" 1>&2
+#    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c postgresql-8.4" 1>&2
+#    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
+#    echo 1>&2
+#fi
 
-if [ -z "$OPENSHIFT_POSTGRESQL_DB_HOST" ]
-then
-    exit 5
-fi
+#if [ -z "$OPENSHIFT_POSTGRESQL_DB_HOST" ]
+#then
+#    exit 5
+#fi
  
 
 # Confirm database exists, if not create it
-if ! psql -c "select * from posts;" "$OPENSHIFT_APP_NAME" > /dev/null 2>&1
-then
-    echo
-    echo "Database schema not found, importing 'cake.sql' schema."
-    echo
-    psql -a -f "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/cake.sql" "$OPENSHIFT_APP_NAME"
-    echo
-    echo "done."
-else
-    echo "Database found, skipping import."
-fi
+#if ! psql -c "select * from posts;" "$OPENSHIFT_APP_NAME" > /dev/null 2>&1
+#then
+#    echo
+#    echo "Database schema not found, importing 'cake.sql' schema."
+#    echo
+#    psql -a -f "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/cake.sql" "$OPENSHIFT_APP_NAME"
+#    echo
+#    echo "done."
+#else
+#    echo "Database found, skipping import."
+#fi
